-- TutorSnap PostgreSQL baseline schema for Supabase.
-- Additive only: this project is newly created and currently empty.

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" VARCHAR(64) NOT NULL UNIQUE,
  name TEXT,
  email VARCHAR(320),
  "loginMethod" VARCHAR(64),
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "lastSignedIn" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "appearanceSettings" TEXT
);

CREATE TABLE IF NOT EXISTS public.referral_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  uses INTEGER NOT NULL DEFAULT 0,
  "maxUses" INTEGER NOT NULL DEFAULT 999,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fraud_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  "alertType" VARCHAR(50) NOT NULL,
  "ipAddress" VARCHAR(45),
  "deviceId" VARCHAR(255),
  severity VARCHAR(20) NOT NULL DEFAULT 'medium',
  description TEXT,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  "actionTaken" VARCHAR(100),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.redemption_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  "codeId" BIGINT,
  code VARCHAR(50) NOT NULL,
  "ipAddress" VARCHAR(45),
  "deviceId" VARCHAR(255),
  "userAgent" TEXT,
  success BOOLEAN NOT NULL DEFAULT TRUE,
  "failureReason" VARCHAR(100),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.otp_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  "hashedCode" VARCHAR(64) NOT NULL,
  purpose VARCHAR(20) NOT NULL DEFAULT 'signin',
  "expiresAt" TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  "ipAddress" VARCHAR(45),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.otp_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  purpose VARCHAR(20) NOT NULL DEFAULT 'signin',
  "ipAddress" VARCHAR(45),
  outcome VARCHAR(30) NOT NULL DEFAULT 'sent',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.scheduler_locks (
  "jobName" VARCHAR(100) PRIMARY KEY,
  "instanceId" VARCHAR(200) NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "acquiredAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.aire_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  difficulty INTEGER NOT NULL,
  subject VARCHAR(64) NOT NULL DEFAULT 'other',
  steps INTEGER NOT NULL DEFAULT 1,
  rating INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.aire_subject_calibration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  subject VARCHAR(64) NOT NULL DEFAULT 'other',
  multiplier VARCHAR(8) NOT NULL DEFAULT '1.0',
  "sampleCount" INTEGER NOT NULL DEFAULT 0,
  "lastFeedbackAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.solve_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  problem TEXT NOT NULL,
  answer TEXT,
  subject VARCHAR(64),
  "solutionJson" TEXT,
  bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
  "solvedAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  "sessionId" VARCHAR(64) NOT NULL,
  title VARCHAR(255),
  subject VARCHAR(64),
  "gradeLevel" VARCHAR(32),
  "messagesJson" TEXT NOT NULL,
  tags TEXT,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  "messageCount" INTEGER NOT NULL DEFAULT 0,
  "sessionCreatedAt" TIMESTAMPTZ NOT NULL,
  "sessionUpdatedAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  "progressJson" TEXT NOT NULL,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  "bookmarkId" VARCHAR(64) NOT NULL,
  "itemJson" TEXT NOT NULL,
  subject VARCHAR(64),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  "noteId" VARCHAR(64) NOT NULL,
  "noteJson" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  "revenueCatUserId" VARCHAR(255) NOT NULL,
  "productId" VARCHAR(255) NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','cancelled','expired','refunded')),
  "isInGracePeriod" BOOLEAN NOT NULL DEFAULT FALSE,
  "expiresAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.classrooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publicId" VARCHAR(36) NOT NULL UNIQUE,
  "teacherId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  "joinCode" VARCHAR(8) NOT NULL UNIQUE,
  subject VARCHAR(64) NOT NULL,
  "gradeLevel" VARCHAR(32),
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.classroom_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "classroomId" BIGINT NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('teacher','learner')),
  "joinedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT classroom_members_class_user_uq UNIQUE ("classroomId", "userId")
);

CREATE TABLE IF NOT EXISTS public.assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publicId" VARCHAR(36) NOT NULL UNIQUE,
  "classroomId" BIGINT NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  "createdByUserId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title VARCHAR(160) NOT NULL,
  instructions TEXT NOT NULL,
  subject VARCHAR(64) NOT NULL,
  "dueAt" TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  "publishedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.assignment_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publicId" VARCHAR(36) NOT NULL UNIQUE,
  "assignmentId" BIGINT NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','complete')),
  "responseText" TEXT,
  "submittedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT assignment_submissions_assignment_user_uq UNIQUE ("assignmentId", "userId")
);

CREATE TABLE IF NOT EXISTS public.assignment_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publicId" VARCHAR(36) NOT NULL UNIQUE,
  "assignmentId" BIGINT NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  "authorUserId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "deletedAt" TIMESTAMPTZ,
  "deletedByUserId" BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  "moderationReason" VARCHAR(64),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.classroom_join_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  "ipAddress" VARCHAR(45),
  "codeHash" VARCHAR(64) NOT NULL,
  outcome VARCHAR(32) NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_otp_email_purpose ON public.otp_codes(email, purpose, "createdAt");
CREATE INDEX IF NOT EXISTS idx_otp_expires ON public.otp_codes("expiresAt");
CREATE INDEX IF NOT EXISTS idx_audit_email_created ON public.otp_audit(email, "createdAt");
CREATE INDEX IF NOT EXISTS idx_audit_ip_created ON public.otp_audit("ipAddress", "createdAt");
CREATE INDEX IF NOT EXISTS aire_feedback_userid_idx ON public.aire_feedback("userId");
CREATE INDEX IF NOT EXISTS aire_calib_userid_subject_idx ON public.aire_subject_calibration("userId", subject);
CREATE INDEX IF NOT EXISTS solve_history_userid_idx ON public.solve_history("userId", "solvedAt");
CREATE INDEX IF NOT EXISTS chat_sessions_userid_idx ON public.chat_sessions("userId");
CREATE INDEX IF NOT EXISTS chat_sessions_sessionid_idx ON public.chat_sessions("userId", "sessionId");
CREATE INDEX IF NOT EXISTS user_bookmarks_userid_idx ON public.user_bookmarks("userId");
CREATE INDEX IF NOT EXISTS user_bookmarks_bookmarkid_idx ON public.user_bookmarks("userId", "bookmarkId");
CREATE INDEX IF NOT EXISTS user_notes_userid_idx ON public.user_notes("userId");
CREATE INDEX IF NOT EXISTS user_notes_noteid_idx ON public.user_notes("userId", "noteId");
CREATE INDEX IF NOT EXISTS idx_subscriptions_userid ON public.subscriptions("userId");
CREATE INDEX IF NOT EXISTS idx_subscriptions_rcuserid ON public.subscriptions("revenueCatUserId");
CREATE INDEX IF NOT EXISTS classrooms_teacher_idx ON public.classrooms("teacherId");
CREATE INDEX IF NOT EXISTS classrooms_active_updated_idx ON public.classrooms("isActive", "updatedAt");
CREATE INDEX IF NOT EXISTS classroom_members_user_joined_idx ON public.classroom_members("userId", "joinedAt");
CREATE INDEX IF NOT EXISTS classroom_members_class_role_idx ON public.classroom_members("classroomId", role);
CREATE INDEX IF NOT EXISTS assignments_class_status_due_idx ON public.assignments("classroomId", status, "dueAt");
CREATE INDEX IF NOT EXISTS assignments_class_updated_idx ON public.assignments("classroomId", "updatedAt");
CREATE INDEX IF NOT EXISTS assignment_submissions_status_idx ON public.assignment_submissions("assignmentId", status);
CREATE INDEX IF NOT EXISTS assignment_submissions_user_updated_idx ON public.assignment_submissions("userId", "updatedAt");
CREATE INDEX IF NOT EXISTS assignment_comments_assignment_created_idx ON public.assignment_comments("assignmentId", "createdAt", id);
CREATE INDEX IF NOT EXISTS assignment_comments_author_created_idx ON public.assignment_comments("authorUserId", "createdAt");
CREATE INDEX IF NOT EXISTS classroom_join_user_created_idx ON public.classroom_join_attempts("userId", "createdAt");
CREATE INDEX IF NOT EXISTS classroom_join_ip_created_idx ON public.classroom_join_attempts("ipAddress", "createdAt");
CREATE INDEX IF NOT EXISTS classroom_join_hash_created_idx ON public.classroom_join_attempts("codeHash", "createdAt");
